# Generated by Django 6.0.4 on 2026-04-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uploaded_image_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
